-- MySQL Script generated by MySQL Workbench
-- Sun May 20 17:25:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbsistena
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsistena
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsistena` DEFAULT CHARACTER SET utf8 ;
USE `dbsistena` ;

-- -----------------------------------------------------
-- Table `dbsistena`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistena`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistena`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistena`.`articulo` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `codigo` VARCHAR(50) NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `imagen` VARCHAR(45) NULL,
  `condicion` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idarticulo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_articulo_categorio_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_articulo_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `dbsistena`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistena`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistena`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `tipo_persona` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NULL,
  `num_documento` VARCHAR(20) NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistena`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistena`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `cargo` VARCHAR(20) NULL,
  `login` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(70) NOT NULL,
  `condicion` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistena`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistena`.`ingreso` (
  `idingreso` INT NOT NULL AUTO_INCREMENT,
  `idproveedor` INT NOT NULL,
  `idusuario` INT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(7) NULL,
  `num_comprobante` VARCHAR(10) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `total_compra` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idingreso`),
  INDEX `fk_ingreso_persona_idx` (`idproveedor` ASC),
  INDEX `fk_ingreso_usuario_idx` (`idusuario` ASC),
  CONSTRAINT `fk_ingreso_persona`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `dbsistena`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbsistena`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistena`.`ingresodetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistena`.`ingresodetalle` (
  `idingresodetalle` INT NOT NULL AUTO_INCREMENT,
  `idingreso` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_compra` DECIMAL(11,2) NOT NULL,
  `precio_venta` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idingresodetalle`),
  INDEX `fk_ingresodetalle_ingreso_idx` (`idingreso` ASC),
  INDEX `fk_ingresodetalle_articulo_idx` (`idarticulo` ASC),
  CONSTRAINT `fk_ingresodetalle_ingreso`
    FOREIGN KEY (`idingreso`)
    REFERENCES `dbsistena`.`ingreso` (`idingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresodetalle_articulo`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `dbsistena`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistena`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistena`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(7) NULL,
  `num_comprobante` VARCHAR(20) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NOT NULL,
  `total_venta` DECIMAL(11,2) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idventa`),
  INDEX `fk_venta_cliente_idx` (`idcliente` ASC),
  INDEX `fk_venta_usuario_idx` (`idusuario` ASC),
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `dbsistena`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbsistena`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistena`.`ventadetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistena`.`ventadetalle` (
  `idventadetalle` INT NOT NULL AUTO_INCREMENT,
  `id_venta` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_venta` DECIMAL(11,2) NOT NULL,
  `descuento` DECIMAL(11,2) NULL,
  PRIMARY KEY (`idventadetalle`),
  INDEX `fk_ventadetalle_venta_idx` (`id_venta` ASC),
  INDEX `fk_ventadetalle_idx` (`idarticulo` ASC),
  CONSTRAINT `fk_ventadetalle_venta`
    FOREIGN KEY (`id_venta`)
    REFERENCES `dbsistena`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventadetalle_articulo`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `dbsistena`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistena`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistena`.`permiso` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL,
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistena`.`permisousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistena`.`permisousuario` (
  `idpermisousuario` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idpermiso` INT NOT NULL,
  PRIMARY KEY (`idpermisousuario`),
  INDEX `fk_permisousuario_usuario_idx` (`idusuario` ASC),
  INDEX `fk_permisousuario_permiso_idx` (`idpermiso` ASC),
  CONSTRAINT `fk_permisousuario_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `dbsistena`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permisousuario_permiso`
    FOREIGN KEY (`idpermiso`)
    REFERENCES `dbsistena`.`permiso` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
